# Genetic Algorithms

This jupyter notebook applies genetic algorithm to the Makespan Problem. Genetic Algorithms are search methods based on selection and genetics. We define "chromosomes" as candidate solutions. The Genetic Algorithm

## 1. Initialization

In [24]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
def define_machines(machine_number):
    # defining machine
    machines = []

    for i in range(machine_number):
        machines.append(i)
        
    return machines
    
print(define_machines(3))


[0, 1, 2]


In [3]:
# defining jobs
# jobs = []

# for i in range(1,301)
#     jobs.append(i)
    
# jobs

In [69]:
def creating_process_times(stack1_border_high,stack1_border_low,stack1_number,stack2_border_high,stack2_border_low,stack2_number):
    # Assigning random processing times for each job
    stack1 = np.random.randint(stack1_border_low,stack1_border_high, size=stack1_number)
    stack2 = np.random.randint(stack2_border_low,stack2_border_high, size=stack2_number)

    process_times = np.concatenate((stack1 ,stack2), axis=0)
    
    return process_times

##print(creating_process_times(30,10,5))

# time_high
# time_low

In [5]:
def assigning_jobs_to_machines(machine_number,job_number,population_size):
    # Assigning random jobs to machines
    population=[]
    job_locations = []
    #job_locations = np.random.randint(0,machine_number,size = job_number)
    
    for i in range(population_size):
        job_locations = np.random.randint(0,machine_number,size = job_number)
        print(job_locations)
        population.append(job_locations)
        #population= np.append(population job_locations, 0)
        print(population)
        job_locations = []
        
    return population

print(assigning_jobs_to_machines(3,10,3))

[0 2 1 0 0 0 0 2 2 2]
[array([0, 2, 1, 0, 0, 0, 0, 2, 2, 2])]
[1 0 1 0 2 2 0 0 2 2]
[array([0, 2, 1, 0, 0, 0, 0, 2, 2, 2]), array([1, 0, 1, 0, 2, 2, 0, 0, 2, 2])]
[2 0 1 2 1 0 0 2 2 2]
[array([0, 2, 1, 0, 0, 0, 0, 2, 2, 2]), array([1, 0, 1, 0, 2, 2, 0, 0, 2, 2]), array([2, 0, 1, 2, 1, 0, 0, 2, 2, 2])]
[array([0, 2, 1, 0, 0, 0, 0, 2, 2, 2]), array([1, 0, 1, 0, 2, 2, 0, 0, 2, 2]), array([2, 0, 1, 2, 1, 0, 0, 2, 2, 2])]


In [6]:
# calculate processing time
def compute_time(process_times, job_locations,machines):
    time = 0
    max_time = 0
    for i in range(len(machines)):
       
        for j in range(len(job_locations)):
            if job_locations[j] == i:
                time = time + process_times[j]
                
        if time > max_time:
            max_time = time
    
        print(time)
        time = 0               
                
            
    return max_time

In [7]:
time = compute_time(process_times, job_locations,machines)
time


# array = [2, 3, 4, 5]
# array[1]

NameError: name 'process_times' is not defined

In [53]:
def initialize(population_size,machine_number,job_number):
    define_machines(machine_number)
    creating_process_times(30,10,2,50,10,2)
    chromosomes = []
    
    for i in range(population_size):
        job_locations = assigning_jobs_to_machines(machine_number,job_number,2)
        chromosomes.append(np.copy(job_locations))
    
    return chromosomes
print(initialize(5,3,5))

[2 2 1 0 1]
[array([2, 2, 1, 0, 1])]
[1 2 1 2 0]
[array([2, 2, 1, 0, 1]), array([1, 2, 1, 2, 0])]
0
[2 0 0 0 2]
[array([2, 0, 0, 0, 2])]
[0 1 2 1 0]
[array([2, 0, 0, 0, 2]), array([0, 1, 2, 1, 0])]
1
[1 1 1 2 0]
[array([1, 1, 1, 2, 0])]
[2 0 2 2 0]
[array([1, 1, 1, 2, 0]), array([2, 0, 2, 2, 0])]
2
[1 0 2 1 0]
[array([1, 0, 2, 1, 0])]
[0 2 0 2 0]
[array([1, 0, 2, 1, 0]), array([0, 2, 0, 2, 0])]
3
[0 2 0 2 1]
[array([0, 2, 0, 2, 1])]
[1 0 0 2 2]
[array([0, 2, 0, 2, 1]), array([1, 0, 0, 2, 2])]
4
[array([[2, 2, 1, 0, 1],
       [1, 2, 1, 2, 0]]), array([[2, 0, 0, 0, 2],
       [0, 1, 2, 1, 0]]), array([[1, 1, 1, 2, 0],
       [2, 0, 2, 2, 0]]), array([[1, 0, 2, 1, 0],
       [0, 2, 0, 2, 0]]), array([[0, 2, 0, 2, 1],
       [1, 0, 0, 2, 2]])]


## 2. Evaluation

In [9]:
# take the function "compute time" and get fitness level for each chromosome, give back array of fitness values
def evaluate(chromosomes):
    return chromosome_fitness_level

## 3. Selection

In [10]:
def select(chromosomes,chromosome_fitness_level):
    # TODO: take the variable "mating pool" and get this number of chromosomes from the population (Roulette, Tournament)
    # returns array of chromosomes (mating pool)
    select the chromosome according to algorithm like rhoulette wheel selection and return the matin_pool as chromosomes
    chromosome = []
    return chromosomes

SyntaxError: invalid syntax (<ipython-input-10-61bc407ff661>, line 4)

## 4. Recombination

In [11]:
def one_point_crossover(parent1,parent2):
    location = np.random.randint(0,len(parent1))
    child1 = np.copy(parent1)
    child2 = np.copy(parent2)
    for i in range(len(parent1)):
        if i <= location:
            child1[i] = parent1[i]
            child2[i] = parent2[i]
        else:
            child1[i] = parent2[i]
            child2[i] = parent1[i]
            
    return child1,child2  

In [12]:
def uniform_crossover(parent1, parent2):
    location_array = np.random.choice(2, len(parent1))
    child1 = np.copy(parent1)
    child2 = np.copy(parent2)
    for i in range(len(parent1)):
        if location_array[i] == 0:
            child1[i] = parent1[i]
            child2[i] = parent2[i]
        else:
            child1[i] = parent2[i]
            child2[i] = parent1[i]
            
    return child1,child2

In [13]:
def recombine_one_point_crossover(mating_pool,crossover_probability):
    # takes randomly two chromosomes and performs one point crossover / two point
     # crossover probability that two "parents" fuck, if not they just get copied
    # returns children array, same size like mating pool 
    
    children_chromosome = []
    i = 0
    while len(mating_pool) > 0:
        parent1 = mating_pool.pop()
        parent2 = mating_pool.pop()
        
        if random.random() < crossover_probability:
            child1, child2 = one_point_crossover(parent1,parent2)
            children_chromosome.append(child1)
            children_chromosome.append(child2)
        else:
            children_chromosome.append(parent1)
            children_chromosome.append(parent2)
            print(parent1)
            print(parent2)
        i += 1
    
    return children_chromosome

In [14]:
def recombine_uniform_crossover(mating_pool,crossover_probability):
    # takes randomly two chromosomes and performs one point crossover / two point
     # crossover probability that two "parents" fuck, if not they just get copied
    # returns children array, same size like mating pool 
    
    children_chromosome = []
    i = 0
    while len(mating_pool) > 0:
        parent1 = mating_pool.pop()
        parent2 = mating_pool.pop()
        
        if random.random() < crossover_probability:
            child1, child2 = uniform_crossover(parent1,parent2)
            children_chromosome.append(child1)
            children_chromosome.append(child2)
        else:
            children_chromosome.append(parent1)
            children_chromosome.append(parent2)
            print(parent1)
            print(parent2)
        i += 1
    
    return children_chromosome

## 5. Mutation

In [63]:
def flip(child_chromosome,mutation_probability,machine_number):
    mutated_child_chromosome = np.copy(child_chromosome)
    if random.random() < mutation_probability:
        location = np.random.randint(0,len(child_chromosome))
        new_machine_number = np.random.randint(0,machine_number+1)
        mutated_child_chromosome[location] = new_machine_number 
    return mutated_child_chromosome
print(flip([0,1,2,3,0],0.5,4))

[0 1 2 3 3]


In [64]:
def swap(child_chromosome,mutation_probability):
    mutated_child_chromosome = np.copy(child_chromosome)
    if random.random() < mutation_probability:
        location1 = np.random.randint(0,len(child_chromosome))
        location2 = np.random.randint(0,len(child_chromosome))
        while location1 == location2:
                location2 = np.random.randint(0,len(child_chromosome))
        help_variable = mutated_child_chromosome[location1]
        mutated_child_chromosome[location1] = mutated_child_chromosome[location2]
        mutated_child_chromosome[location2] = help_variable
    return mutated_child_chromosome
print(swap([0,1,2,3,0],0.5))

[0 1 2 3 0]


In [86]:
def mutate_flip(child_chromosomes,mutation_probability,machine_number):
    # goes through children_chromosome, get changed with mutation probability, ramdom machine_flip / swap
    # gives back children array
    mutateted_child_chromsomes = np.copy(child_chromosomes)
    for i in range(len(child_chromosomes)):
        child_chromosomes[i] = flip(child_chromosomes[i],mutation_probability,machine_number)
    return mutateted_child_chromsomes

In [85]:
def mutate_swap(child_chromosomes,mutation_probability,machine_number):
    # goes through children_chromosome, get changed with mutation probability, ramdom machine_flip / swap
    # gives back children array
    mutateted_child_chromsomes = np.copy(child_chromosomes)
    for i in range(len(child_chromosomes)):
        print('before flip:',child_chromosomes[i])
        child_chromosomes[i] = swap(child_chromosomes[i],mutation_probability)
        print('after flip:',child_chromosomes[i])
    return mutateted_child_chromsomes

## 6. Replacement

In [16]:
def replace_deleteall(chromosomes,children_chromosomes):
    # gets population & children array, gives back new population
    # delete_all - look at the difference in size between population and children, take the best ones of population to get rid difference, then delete rest and put children in
    # choose_best - look at population and children at same time, choose the best ones of all to get new population
    if len(chromosomes) == len(children_chromosomes):
        new_chromosomes = np.copy(children_chromosomes)
    else:
        new_chromosomes = []
        difference = len(chromosomes)-len(children_chromosomes)
        
        while (len(new_chromosomes) < difference):
            chromosomes_values = evaluate(chromosomes)
            max_value = max(chromosomes_values)
            max_index = chromosomes_values.index(max_value)
            new_chromosomes.append(chromosomes[max_index])
            chromosomes.delete[max_index]
            
        new_chromosomes.extend(children_chromosomes)
    
    return new_chromosomes


def replace_choosebest(chromosomes, children_chromosomes):
    
    new_chromosomes = []
    all_chromosomes =[]
    all_chromosomes.extend(chromosomes)
    all_chromosomes.extend(children_chromosomes)
    
    while (len(new_chromosomes) < len(chromosomes)):
            chromosomes_values = evaluate(all_chromosomes)
            max_value = max(chromosomes_values)
            max_index = chromosomes_values.index(max_value)
            new_chromosomes.append(all_chromosomes[max_index])
            all_chromosomes.delete[max_index]
    
    return new_chromosomes

## 7. Action

In [17]:
#variables
population_size = 5
machine_number = 3
job_number = 5
mating_pool = 4
crossover_probability 
mutation_probability


# Initialization
chromosomes = initialize(population_size,machine_number,job_number)

#start loop

# Evaluation
evaluate(chromosomes)

# Selection
chromosome1 = select()
chromosome2 = select()

# Recombination
recombine()

# Mutation
mutate()

# Replacement
replace()


# convergence: if they don't change after lot of iterations (idea: just look at every 100th one if it stopped changing)

NameError: name 'crossover_probability' is not defined