# Genetic Algorithms

This jupyter notebook applies genetic algorithm to the Makespan Problem. Genetic Algorithms are search methods based on selection and genetics. We define "chromosomes" as candidate solutions. The Genetic Algorithm

## 1. Initialization

In [1]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt
from datetime import datetime

In [24]:
def define_machines(machine_number):
    # defining machine
    machines = []

    for i in range(machine_number):
        machines.append(i)
        
    return machines
    
print(define_machines(2))


[0, 1, 2]


In [25]:
# defining jobs
# jobs = []

# for i in range(1,301)
#     jobs.append(i)
    
# jobs

In [26]:
def creating_process_times(stack1_border_high,stack1_border_low,stack1_number,stack2_border_high,stack2_border_low,stack2_number):
    # Assigning random processing times for each job
    stack1 = np.random.randint(stack1_border_low,stack1_border_high+1, size=stack1_number)
    stack2 = np.random.randint(stack2_border_low,stack2_border_high+1, size=stack2_number)

    process_times = np.concatenate((stack1 ,stack2), axis=0)
    
    return process_times

print(creating_process_times(4,1,10,8,5,20))

# time_high
# time_low

In [27]:
def initialize(machine_number,job_number,population_size):
    # Assigning random jobs to machines
    population=[]
    chromosone = []
    #job_locations = np.random.randint(0,machine_number,size = job_number)
    
    for i in range(population_size):
        chromosone = np.random.randint(0,machine_number,size = job_number)
        #print(chromosone)
        population.append(chromosone)
        #population= np.append(population job_locations, 0)
        #print(population)
        job_locations = []
        
    return population

print(initialize(2,30,100))

[2 0 1 0 2 0 2 1 2 1]
[array([2, 0, 1, 0, 2, 0, 2, 1, 2, 1])]
[1 1 0 1 2 1 1 1 0 0]
[array([2, 0, 1, 0, 2, 0, 2, 1, 2, 1]), array([1, 1, 0, 1, 2, 1, 1, 1, 0, 0])]
[1 2 1 1 0 2 1 0 2 0]
[array([2, 0, 1, 0, 2, 0, 2, 1, 2, 1]), array([1, 1, 0, 1, 2, 1, 1, 1, 0, 0]), array([1, 2, 1, 1, 0, 2, 1, 0, 2, 0])]
[array([2, 0, 1, 0, 2, 0, 2, 1, 2, 1]), array([1, 1, 0, 1, 2, 1, 1, 1, 0, 0]), array([1, 2, 1, 1, 0, 2, 1, 0, 2, 0])]


In [28]:
# calculate processing time
def evaluate_chromosones(process_times, chromosone,machines):
    time = 0
    max_time = 0
    for i in range(machines):
       
        for j in range(len(chromosone)):
            if chromosone[j] == i:
                time = time + process_times[j]
                
        if time > max_time:
            max_time = time
    
        #print(time)
        time = 0               
                
    chromosome_fitness_level=max_time        
    return chromosome_fitness_level
print(evaluate_chromosones([ 5, 5, 5, 7, 7, 6, 5],[0, 1, 1, 0, 0, 1, 0],2))

## 2. Evaluation

In [31]:

# take the function "compute time" and get fitness level for each chromosome, give back array of fitness values
def evaluate(population,process_times,machines):
    print(process_times)
    population_fitness = []
    #print(np.nditer(population))
    print(population)
    for i in (population):
        print(evaluate_chromosones(process_times, i,machines))
        population_fitness.append(evaluate_chromosones(process_times, i,machines))
        print(population_fitness)
    return population_fitness


# evaluate_chromosones(process_times, chromosone,machines):
# creating_process_times(stack1_border_high,stack1_border_low,stack1_number,stack2_border_high,stack2_border_low,stack2_number):
# initialize(machine_number,job_number,population_size):
evaluate(initialize(2,10,10), creating_process_times(4,1,5,8,5,5),2)

## 3. Selection

In [32]:
def roulette_select(population,population_fitness,mating_pool_size):
    # TODO: take the variable "mating pool" and get this number of chromosomes from the population (Roulette, Tournament)
    # returns array of chromosomes (mating pool)
    
    denominator = np.sum(population_fitness)
    probabilities = np.true_divide(population_fitness, denominator)
    
   
    print(probabilities)
    
    boundaries = []
    boundaries.append(0)
    boundaries[0] = probabilities[0]
    print(boundaries[0])
    for i in range(1,len(probabilities)):
        boundaries.append(0)
        boundaries[i] = probabilities[i]+boundaries[i-1]
    print("boundaries")
    print(boundaries)
    mating_pool = []
    for i in range(mating_pool_size):
        print("rand_mate")
        
        rand_mate = np.random.uniform(0,1)
       # rand_mate = 1
        print(rand_mate)
        for j in range(len(boundaries)):
            if boundaries[j] > rand_mate:
                mating_pool.append(population[j-1])
                break
            if rand_mate == 1:
                mating_pool.append(population[0])
                break
    print(mating_pool)
    
    #select the chromosome according to algorithm like rhoulette wheel selection and return the matin_pool as chromosomes
    
    return mating_pool

population = [[1, 0, 1, 0, 1, 0, 0, 1, 1, 1], [0, 0, 1, 0, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [0, 1, 1, 1, 0, 1, 0, 0, 1, 1], [1, 0, 0, 0, 0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 0, 0, 0, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 0, 1], [1, 1, 0, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 1, 0, 1]]
population_fitness = [27, 28, 31, 27, 27, 30, 23, 23, 25, 24]

roulette_select(population,population_fitness,5)

SyntaxError: invalid syntax (<ipython-input-32-61bc407ff661>, line 4)

In [ ]:
def tournament_select(population,population_fitness,mating_pool_size):
    # TODO: take the variable "mating pool" and get this number of chromosomes from the population (Roulette, Tournament)
    # returns array of chromosomes (mating pool)

    mating_pool=[]
    highest_fitness_level= 0
    old_highest_fitnesslevel_location=[]
    for i in range(0,mating_pool_size):
        for j in range(0,len(population_fitness)):
            if population_fitness[j]>highest_fitness_level and j not in old_highest_fitnesslevel_location:
                highest_fitness_level=population_fitness[j]
                print(highest_fitness_level)
        mating_pool.append(highest_fitness_level)
        old_highest_fitnesslevel_location.append(j)
        print(old_highest_fitnesslevel_location)
        highest_fitness_level=0
                       
                       
                       
   # mydict= dict(zip(population,population_fitness))
   # print(mydict)
    #for key, value in sorted(mydict.iteritems(), key=lambda (k,v): (v,k)):
     #   print "%s: %s" % (key, value)
    
    
    return mating_pool 
   # return mydict



population = [[1, 0, 1, 0, 1, 0, 0, 1, 1, 1], [0, 0, 1, 0, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [0, 1, 1, 1, 0, 1, 0, 0, 1, 1], [1, 0, 0, 0, 0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 0, 0, 0, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 0, 1], [1, 1, 0, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 1, 0, 1]]
population_fitness = [27, 28, 31, 27, 27, 30, 23, 23, 25, 24]

tournament_select(population,population_fitness,5)

# Issues:
#  problem is that saving the old best fitness level locations in an array and checking for that does not work yet.
# and also in the append of the mating pool it's' still appending the
# fitnesslevel of las position of the j loop when we actually want to append population[j]

In [ ]:
def tournament_select(population,population_fitness,mating_pool_size):

    mydict= dict(zip(population_fitness,population))
    print(mydict)
 
    sorted_dict = sorted(mydict.items())
#     print(sorted_dict)

#     sorted_mating_pool = sorted_dict.items()
#     sorted_mating_pool = mydict.values()
#     sorted_dict.values()
#     try:
#         del sorted_dict['key']
#     except KeyError:
#         pass
#     if 'key' in sorted_dict: 
#         del sorted_dict['key']
#     population_fitness = list(map(int, population_fitness))
    for i in range(len(population_fitness),0,1):
#         sorted_dict.pop(population_fitness[i])
        try:
            del sorted_dict.key[i]
        except KeyError:
            pass
#     sorted_mating_pool = sorted_dict.pop('key')
#     print(sorted_mating_pool)
    print(sorted_dict)
     return sorted_dict



population = [[1, 0, 1, 0, 1, 0, 0, 1, 1, 1], [0, 0, 1, 0, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [0, 1, 1, 1, 0, 1, 0, 0, 1, 1], [1, 0, 0, 0, 0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 0, 0, 0, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 0, 1], [1, 1, 0, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 1, 0, 1]]
population_fitness = [27, 28, 31, 27, 27, 30, 23, 23, 25, 24]

tournament_select(population,population_fitness,5)

# Two issues in this code:
#     1. Although i pass 10 values of populationa and corresponding fitness levels, only 7 are present in mydict
#     2. Not able to separate the valuescolumn  from the sorted dict even after using pop and del methods 



## 4. Recombination

In [33]:
def one_point_crossover(parent1,parent2):
    location = np.random.randint(0,len(parent1))
    child1 = np.copy(parent1)
    child2 = np.copy(parent2)
    for i in range(len(parent1)):
        if i <= location:
            child1[i] = parent1[i]
            child2[i] = parent2[i]
        else:
            child1[i] = parent2[i]
            child2[i] = parent1[i]
            
    return child1,child2  

In [34]:
def uniform_crossover(parent1, parent2):
    location_array = np.random.choice(2, len(parent1))
    child1 = np.copy(parent1)
    child2 = np.copy(parent2)
    for i in range(len(parent1)):
        if location_array[i] == 0:
            child1[i] = parent1[i]
            child2[i] = parent2[i]
        else:
            child1[i] = parent2[i]
            child2[i] = parent1[i]
            
    return child1,child2

In [47]:
def recombine_one_point_crossover(mating_pool,crossover_probability):
    # takes randomly two chromosomes and performs one point crossover / two point
     # crossover probability that two "parents" fuck, if not they just get copied
    # returns children array, same size like mating pool 
    
    children_chromosome = []
    i = 0
    while len(mating_pool) > 0:
        parent1 = mating_pool.pop()
        parent2 = mating_pool.pop()
        
        if random.random() < crossover_probability:
            child1, child2 = one_point_crossover(parent1,parent2)
            children_chromosome.append(child1)
            children_chromosome.append(child2)
        else:
            children_chromosome.append(parent1)
            children_chromosome.append(parent2)
            print(parent1)
            print(parent2)
        i += 1
    
    return children_chromosome

In [36]:
def recombine_uniform_crossover(mating_pool,crossover_probability):
    # takes randomly two chromosomes and performs one point crossover / two point
     # crossover probability that two "parents" fuck, if not they just get copied
    # returns children array, same size like mating pool 
    
    children_chromosome = []
    i = 0
    while len(mating_pool) > 0:
        parent1 = mating_pool.pop()
        parent2 = mating_pool.pop()
        
        if random.random() < crossover_probability:
            child1, child2 = uniform_crossover(parent1,parent2)
            children_chromosome.append(child1)
            children_chromosome.append(child2)
        else:
            children_chromosome.append(parent1)
            children_chromosome.append(parent2)
            print(parent1)
            print(parent2)
        i += 1
    
    return children_chromosome

## 5. Mutation

In [84]:
def flip(child_chromosome,mutation_probability,machine_number):
    mutated_child_chromosome = np.copy(child_chromosome)
    if random.random() < mutation_probability:
        location = np.random.randint(0,len(child_chromosome))
        new_machine_number = np.random.randint(0,machine_number+1)
        mutated_child_chromosome[location] = new_machine_number 
    return mutated_child_chromosome
print(flip([0,1,2,3,0],0.5,4))

[0 1 2 3 0]


In [85]:
def swap(child_chromosome,mutation_probability):
    mutated_child_chromosome = np.copy(child_chromosome)
    if random.random() < mutation_probability:
        location1 = np.random.randint(0,len(child_chromosome))
        location2 = np.random.randint(0,len(child_chromosome))
        while location1 == location2:
                location2 = np.random.randint(0,len(child_chromosome))
        help_variable = mutated_child_chromosome[location1]
        mutated_child_chromosome[location1] = mutated_child_chromosome[location2]
        mutated_child_chromosome[location2] = help_variable
    return mutated_child_chromosome
print(swap([0,1,2,3,0],0.5))

[1 0 2 3 0]


In [86]:
def mutate_flip(child_chromosomes,mutation_probability,machine_number):
    # goes through children_chromosome, get changed with mutation probability, ramdom machine_flip / swap
    # gives back children array
    mutated_child_chromosomes = np.copy(child_chromosomes)
    for i in range(len(child_chromosomes)):
        child_chromosomes[i] = flip(child_chromosomes[i],mutation_probability,machine_number)
    return mutated_child_chromosomes

In [87]:
def mutate_swap(child_chromosomes,mutation_probability,machine_number):
    # goes through children_chromosome, get changed with mutation probability, ramdom machine_flip / swap
    # gives back children array
    mutated_child_chromosomes = np.copy(child_chromosomes)
    for i in range(len(child_chromosomes)):
        child_chromosomes[i] = swap(child_chromosomes[i],mutation_probability)
    return mutated_child_chromosomes

## 6. Replacement

In [65]:
def replace_deleteall(chromosomes,children_chromosomes):
    # gets population & children array, gives back new population
    # delete_all - look at the difference in size between population and children, take the best ones of population to get rid difference, then delete rest and put children in
    # choose_best - look at population and children at same time, choose the best ones of all to get new population
    if len(chromosomes) == len(children_chromosomes):
        new_chromosomes = np.copy(children_chromosomes)
    else:
        new_chromosomes = []
        difference = len(chromosomes)-len(children_chromosomes)
        
        while (len(new_chromosomes) < difference):
            chromosomes_values = evaluate(chromosomes)
            max_value = max(chromosomes_values)
            max_index = chromosomes_values.index(max_value)
            new_chromosomes.append(chromosomes[max_index])
            chromosomes.delete[max_index]
            
        new_chromosomes.extend(children_chromosomes)
    
    return new_chromosomes


def replace_choosebest(chromosomes, children_chromosomes):
    
    new_chromosomes = []
    all_chromosomes =[]
    all_chromosomes.extend(chromosomes)
    all_chromosomes.extend(children_chromosomes)
    
    while (len(new_chromosomes) < len(chromosomes)):
            chromosomes_values = evaluate(all_chromosomes)
            max_value = max(chromosomes_values)
            max_index = chromosomes_values.index(max_value)
            new_chromosomes.append(all_chromosomes[max_index])
            all_chromosomes.delete[max_index]
    
    return new_chromosomes

## 7. Action

In [90]:
#variables
population_size = 6
machine_number = 3
job_number = 5
mating_pool = 4
crossover_probability = 0.9
mutation_probability = 0.9

do_recombine_one_point_crossover = False
do_mutate_flip = False
do_replace_deleteall = False

converged = False
count = 0

# Initialization
chromosomes = []
#chromosomes = initialize(population_size,machine_number,job_number)

#start loop
while not converged:
    children_chromosomes = []
    new_chromosomes = []
    # Evaluation
    #evaluate(chromosomes)

    # Selection
    #selected_mating_pool = select()
    selected_mating_pool = assigning_jobs_to_machines(machine_number,job_number,population_size)

    # Recombination
    if do_recombine_one_point_crossover:
        children_chromosomes = recombine_one_point_crossover(selected_mating_pool,crossover_probability)
    else:
        children_chromosomes = recombine_uniform_crossover(selected_mating_pool,crossover_probability)

    # Mutation
    if do_mutate_flip:
        children_chromosomes = mutate_flip(children_chromosomes,mutation_probability,machine_number)
    else:
        children_chromosomes = mutate_swap(children_chromosomes,mutation_probability,machine_number)

    # Replacement
    if do_replace_deleteall:
        new_chromosomes = replace_deleteall(chromosomes,children_chromosomes)
    else:
        new_chromosomes = replace_choosebest(chromosomes,children_chromosomes)

    chromosomes = np.copy(new_chromosomes)
    
    if count == 100:
        if (abs(fitness_value_first - np.amin(evaluate(chromosomes)))) <= 100:
            converged = True
        else:
            count = 0
            fitness_value_first = 0
    elif count == 0:
        fitness_value_first = np.amin(evaluate(chromosomes))
        count += 1
    else:
        count += 1

# convergence: if they don't change after lot of iterations (idea: just look at every 100th one if it stopped changing)

[2 1 1 2 2]
[array([2, 1, 1, 2, 2])]
[2 0 1 0 1]
[array([2, 1, 1, 2, 2]), array([2, 0, 1, 0, 1])]
[0 1 2 2 2]
[array([2, 1, 1, 2, 2]), array([2, 0, 1, 0, 1]), array([0, 1, 2, 2, 2])]
[1 2 1 2 0]
[array([2, 1, 1, 2, 2]), array([2, 0, 1, 0, 1]), array([0, 1, 2, 2, 2]), array([1, 2, 1, 2, 0])]
[1 1 0 2 1]
[array([2, 1, 1, 2, 2]), array([2, 0, 1, 0, 1]), array([0, 1, 2, 2, 2]), array([1, 2, 1, 2, 0]), array([1, 1, 0, 2, 1])]
[2 0 1 2 2]
[array([2, 1, 1, 2, 2]), array([2, 0, 1, 0, 1]), array([0, 1, 2, 2, 2]), array([1, 2, 1, 2, 0]), array([1, 1, 0, 2, 1]), array([2, 0, 1, 2, 2])]
[2 0 1 0 1]
[2 1 1 2 2]


NameError: name 'chromosome_fitness_level' is not defined