# Ant-Colony-Optimization Problem

In [2]:
import pandas as pd
import numpy as np

Importing .txt files and saving them as arrays.

In [37]:
with open('01_tsp.txt', 'r') as t1:
    array1 = []
    for line in t1.readlines():
        y = [int(value) for value in line.split()]
        array1.append(y)

    t1.close()
    array1 = np.array(array1)
    print(array1)

print(array1.shape)
print(type(array1))

[[  0 100 229 ... 379 183 178]
 [100   0 329 ... 479 231 278]
 [229 329   0 ... 150 290  87]
 ...
 [379 479 150 ...   0 248 201]
 [183 231 290 ... 248   0 203]
 [178 278  87 ... 201 203   0]]
(150, 150)
<class 'numpy.ndarray'>
