In [108]:
import numpy as np
from datetime import datetime

In [196]:
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
weight_limit = 400
array_weight = 0
# isinstance(knapsack[0], tuple)
# len(knapsack)

In [10]:
array = np.random.randint(2, size=5)
array

array([1, 1, 0, 0, 0])

# Functions

### Check if random array is smaller than weight = feasability

In [185]:
def check_feasibility(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    
    feasible = weight_limit >= array_weight
    return feasible

### Hill-climbing swap function

In [186]:
def swap(array):  
    best_array = array   
    for i in range(len(best_array)):
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        if(i < (len(best_array)-1)): 
            dummy_array[i] = dummy_array[i+1]
            dummy_array[i+1] = dummy_var
        else:
            dummy_array[i] = dummy_array[i-len(best_array)]
            dummy_array[i-len(best_array)] = dummy_var
        
        
        if check_feasibility(dummy_array, knapsack) == True:
            print(dummy_array)
            print(getWeightfromArray(dummy_array,knapsack))
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                print('better_array_found')
    return best_array

### First-choice-hill-climbing swap function

In [187]:
def fcSwap(array):
    best_array = array   
    for i in range(len(best_array)):
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        if(i < (len(best_array)-1)): 
            dummy_array[i] = dummy_array[i+1]
            dummy_array[i+1] = dummy_var
        else:
            dummy_array[i] = dummy_array[i-len(best_array)]
            dummy_array[i-len(best_array)] = dummy_var
        
        
        if check_feasibility(dummy_array, knapsack) == True:
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                break
    return best_array

### Hill-climbing transposition function

In [188]:
def transp(array):  
    best_array = array   
    for i in range(len(best_array)):
       
            for j in range(len(best_array)):
              
                dummy_array = np.copy(best_array)
                dummy_var = dummy_array[i]
                dummy_array[i] = dummy_array[j]
                dummy_array[j] = dummy_var

                if check_feasibility(dummy_array, knapsack) == True:
                    if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                        best_array = dummy_array
                
    return best_array

### First-choice-hill-climbing transposition function

In [189]:
def transp(array):  
    best_array = array   
    for i in range(len(best_array)):
       
            for j in range(len(best_array)):
              
                dummy_array = np.copy(best_array)
                dummy_var = dummy_array[i]
                dummy_array[i] = dummy_array[j]
                dummy_array[j] = dummy_var

                if check_feasibility(dummy_array, knapsack) == True:
                    if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                        best_array = dummy_array
                        break
                
    return best_array

### Get Knapsack Value

In [190]:
def getValuefromArray(array, knapsack): 
    array_value = 0
    for i in range(len(knapsack)):
        knapsack_value = knapsack[i]
        dummy = array[i]*knapsack_value[1]
        array_value = array_value + dummy
    
    return array_value

In [191]:
# checking if function works
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
test = knapsack[0]
test[1]
array = np.random.randint(2, size=5)
print(array)
print(array[0])
getValuefromArray(array, knapsack)

[1 0 1 1 0]
1


12000

### Get Knapsack Weight

In [192]:
def getWeightfromArray(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    return array_weight

# Action

In [205]:

feasible = False
converged = False
count = 0
start = datetime.now()
while(not feasible):
    array = np.random.randint(2, size=5)
    feasible = check_feasibility(array, knapsack)
print(array)
while(not converged):   
    count += 1
    print(count)
    best_array = transp(array)
    converged = getValuefromArray(best_array, knapsack) <= getValuefromArray(array, knapsack)
    array = best_array
    

print(array)
print(getValuefromArray(array, knapsack))
print(getWeightfromArray(array, knapsack))
print(count)
print(datetime.now() - start)


[1 1 0 0 1]
1
2
3
[1 0 1 1 0]
12000
301
3
0:00:00.015625


# Test

In [85]:
def swaptest(array):  
    best_array = array   
    for i in range(len(best_array)-1):
        
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        print(dummy_var)
        dummy_array[i] = dummy_array[i+1]
        print(dummy_array[i])
        dummy_array[i+1] = dummy_var
        print(dummy_array[i+1])
        #print("dummy array before feasibility")
        #print(dummy_array)
        if check_feasibility(dummy_array, knapsack):
            print("dummy")
            print(dummy_array)
            print("dummy array after feasibility check")
            print(getValuefromArray(dummy_array,knapsack))
            print("best array after feasibility check")
            print(getValuefromArray(best_array,knapsack))
            print("best")
            print(best_array)
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                print("test")
                
    return best_array

In [6]:
arraytest1 = np.random.randint(2, size=5)
arraytest2 = arraytest1
arraytest3 = np.copy(arraytest1)
arraytest1[0] = 2
print(arraytest1)
print(arraytest2)
print(arraytest3)

[2 0 0 0 0]
[2 0 0 0 0]
[1 0 0 0 0]
