In [77]:
import numpy as np

In [78]:
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
weight_limit = 400
array_weight = 0
# isinstance(knapsack[0], tuple)
# len(knapsack)

In [79]:
array = np.random.randint(2, size=5)
array

array([1, 0, 1, 0, 0])

# Functions

### Check if random array is smaller than weight = feasability

In [80]:
def check_feasibility(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    
    feasible = weight_limit >= array_weight
    return feasible

### Hill-climbing swap function

In [81]:
def swap(array):  
    best_array = array   
    for i in range(len(array)-1):
        dummy_array = array
        dummy_var = dummy_array[i]
        dummy_array[i] = dummy_array[i+1]
        dummy_array[i+1] = dummy_var
        
        if check_feasibility(dummy_array, knapsack) == True:
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                print("test")
    return best_array

### First-choice-hill-climbing swap function

In [82]:
def fcSwap(array):
    best_array = array   
    for i in range(len(array)):
        dummy_array = array
        dummy_var = dummy_array[i]
        dummy_array[i] = dummy_array[i+1]
        dummy_array[i+1] = dummy_var
    
        if check_feasibility(dummy_array, knapsack):
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                break
    return best_array

### Get Knapsack Value

In [83]:
def getValuefromArray(array, knapsack): 
    array_value = 0
    for i in range(len(knapsack)):
        knapsack_value = knapsack[i]
        dummy = array[i]*knapsack_value[1]
        array_value = array_value + dummy
    
    return array_value

In [84]:
# checking if function works
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
test = knapsack[0]
test[1]
array = np.random.randint(2, size=5)
print(array)
print(array[0])
getValuefromArray(array, knapsack)

[0 1 1 0 0]
0


3000

### Get Knapsack Weight

In [85]:
def getWeightfromArray(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    return array_weight

# Action

In [103]:
feasible = False
converged = False
while(not feasible):
    array = np.random.randint(2, size=5)
    feasible = check_feasibility(array, knapsack)
print(array)
while(not converged):   
    best_array = swaptest(array)
    converged = getValuefromArray(best_array, knapsack) <= getValuefromArray(array, knapsack)
    array = best_array

print(array)
print(getValuefromArray(array, knapsack))
print(getWeightfromArray(array, knapsack))

[0 0 1 0 1]
0
0
0
dummy
[0 0 1 0 1]
dummy array after feasibility check
6000
best array after feasibility check
6000
best
[0 0 1 0 1]
0
1
0
dummy
[0 1 0 0 1]
dummy array after feasibility check
5000
best array after feasibility check
5000
best
[0 1 0 0 1]
0
0
0
dummy
[0 1 0 0 1]
dummy array after feasibility check
5000
best array after feasibility check
5000
best
[0 1 0 0 1]
0
1
0
dummy
[0 1 0 1 0]
dummy array after feasibility check
6000
best array after feasibility check
6000
best
[0 1 0 1 0]
[0 1 0 1 0]
6000
210


In [101]:
def swaptest(array):  
    best_array = array   
    for i in range(len(best_array)-1):
        
        dummy_array = best_array
        dummy_var = dummy_array[i]
        print(dummy_var)
        dummy_array[i] = dummy_array[i+1]
        print(dummy_array[i])
        dummy_array[i+1] = dummy_var
        print(dummy_array[i+1])
        #print("dummy array before feasibility")
        #print(dummy_array)
        if check_feasibility(dummy_array, knapsack):
            print("dummy")
            print(dummy_array)
            print("dummy array after feasibility check")
            print(getValuefromArray(dummy_array,knapsack))
            print("best array after feasibility check")
            print(getValuefromArray(best_array,knapsack))
            print("best")
            print(best_array)
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                print("test")
                
    return best_array