In [2]:
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [3]:
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
weight_limit = 400
array_weight = 0
# isinstance(knapsack[0], tuple)
# len(knapsack)

In [4]:
array = np.random.randint(2, size=5)
array

array([1, 1, 1, 1, 0])

# Functions

### Check if random array is smaller than weight = feasability

In [5]:
def check_feasibility(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    
    feasible = weight_limit >= array_weight
    return feasible

### Hill-climbing swap function

In [37]:
def swap(array):  
    best_array = array   
    for i in range(len(best_array)):
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        if(i < (len(best_array)-1)): 
            dummy_array[i] = dummy_array[i+1]
            dummy_array[i+1] = dummy_var
        else:
            dummy_array[i] = dummy_array[i-len(best_array)]
            dummy_array[i-len(best_array)] = dummy_var
        
        
        if check_feasibility(dummy_array, knapsack) == True:
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
    return best_array

### First-choice-hill-climbing swap function

In [7]:
def fcSwap(array):
    best_array = array   
    for i in range(len(best_array)):
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        if(i < (len(best_array)-1)): 
            dummy_array[i] = dummy_array[i+1]
            dummy_array[i+1] = dummy_var
        else:
            dummy_array[i] = dummy_array[i-len(best_array)]
            dummy_array[i-len(best_array)] = dummy_var
        
        
        if check_feasibility(dummy_array, knapsack) == True:
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                break
    return best_array

### Hill-climbing transposition function

In [8]:
def transp(array):  
    best_array = array   
    for i in range(len(best_array)):
       
            for j in range(len(best_array)):
              
                dummy_array = np.copy(best_array)
                dummy_var = dummy_array[i]
                dummy_array[i] = dummy_array[j]
                dummy_array[j] = dummy_var

                if check_feasibility(dummy_array, knapsack) == True:
                    if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                        best_array = dummy_array
                
    return best_array

### First-choice-hill-climbing transposition function

In [14]:
def fcTransp(array):  
    best_array = array   
    for i in range(len(best_array)):
       
            for j in range(len(best_array)):
              
                dummy_array = np.copy(best_array)
                dummy_var = dummy_array[i]
                dummy_array[i] = dummy_array[j]
                dummy_array[j] = dummy_var

                if check_feasibility(dummy_array, knapsack) == True:
                    if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                        best_array = dummy_array
                        break
                
    return best_array

### Get Knapsack Value

In [10]:
def getValuefromArray(array, knapsack): 
    array_value = 0
    for i in range(len(knapsack)):
        knapsack_value = knapsack[i]
        dummy = array[i]*knapsack_value[1]
        array_value = array_value + dummy
    
    return array_value

In [11]:
# checking if function works
knapsack = {0: (1, 5000), 1: (10, 1000), 2: (100, 2000), 3: (200, 5000), 4: (300, 4000)}
test = knapsack[0]
test[1]
array = np.random.randint(2, size=5)
print(array)
print(array[0])
getValuefromArray(array, knapsack)

[1 1 0 0 0]
1


6000

### Get Knapsack Weight

In [12]:
def getWeightfromArray(array, knapsack):
    array_weight = 0
    for i in range(len(knapsack)):
        knapsack_weight = knapsack[i]
        dummy = array[i]*knapsack_weight[0]
        array_weight = array_weight + dummy
    return array_weight

# Action

In [16]:
feasible = False
converged = False
count = 0
start = datetime.now()
while(not feasible):
    array = np.random.randint(2, size=5)
    feasible = check_feasibility(array, knapsack)
print(array)
while(not converged):   
    count += 1
    best_array = fcTransp(array)
    converged = getValuefromArray(best_array, knapsack) <= getValuefromArray(array, knapsack)
    array = best_array

totalCount += count
totalValue += getValuefromArray(array, knapsack)
totalWeight += getWeightfromArray(array, knapsack)
totalTime += datetime.now() - start
print(array)
print(getValuefromArray(array, knapsack))
print(getWeightfromArray(array, knapsack))
print(count)
print(datetime.now() - start)

[0 0 1 1 0]
[1 0 0 1 0]
10000
201
2
0:00:00.015626


# Action Loop 100

In [41]:
totalCount = 0
totalValue = 0
totalWeight = 0
totalTime = datetime.now() - datetime.now()


for x in range(99):
    feasible = False
    converged = False
    count = 0
    start = datetime.now()
    while(not feasible):
        array = np.random.randint(2, size=5)
        feasible = check_feasibility(array, knapsack)
    #print(array)
    while(not converged):   
        count += 1
        best_array = swap(array)
        converged = getValuefromArray(best_array, knapsack) <= getValuefromArray(array, knapsack)
        array = best_array

    totalCount += count
    totalValue += getValuefromArray(array, knapsack)
    totalWeight += getWeightfromArray(array, knapsack)
    totalTime += datetime.now() - start
    #print(array)
    #print(getValuefromArray(array, knapsack))
    #print(getWeightfromArray(array, knapsack))
    #print(count)
    #print(datetime.now() - start)

print('100 Runs:')
print('Total Count:',totalCount)
print('Average Count:',totalCount / 100)
print('Total Value:',totalValue)
print('Average Value:',totalValue / 100)
print('Total Weight:',totalWeight)
print('Average Weight:',totalWeight / 100)
print('Total Time:',totalTime)
print('Average Time:',totalTime / 100)

100 Runs:
Total Count: 174
Average Count: 1.74
Total Value: 874000
Average Value: 8740.0
Total Weight: 20506
Average Weight: 205.06
Total Time: 0:00:00.078129
Average Time: 0:00:00.000781


# Boxplots

In [43]:
spread = np.random.randint(3, size=100)
center = 2
flier_high = np.random.randint(3, size=100)
flier_low = np.random.randint(3, size=100)
data = np.concatenate((spread, center, flier_high, flier_low), 0)


plt.boxplot(data)
plt.show()

ValueError: all the input arrays must have same number of dimensions

# Test

In [85]:
def swaptest(array):  
    best_array = array   
    for i in range(len(best_array)-1):
        
        dummy_array = np.copy(best_array)
        dummy_var = dummy_array[i]
        print(dummy_var)
        dummy_array[i] = dummy_array[i+1]
        print(dummy_array[i])
        dummy_array[i+1] = dummy_var
        print(dummy_array[i+1])
        #print("dummy array before feasibility")
        #print(dummy_array)
        if check_feasibility(dummy_array, knapsack):
            print("dummy")
            print(dummy_array)
            print("dummy array after feasibility check")
            print(getValuefromArray(dummy_array,knapsack))
            print("best array after feasibility check")
            print(getValuefromArray(best_array,knapsack))
            print("best")
            print(best_array)
            if getValuefromArray(dummy_array, knapsack) > getValuefromArray(best_array, knapsack):
                best_array = dummy_array
                print("test")
                
    return best_array

In [6]:
arraytest1 = np.random.randint(2, size=5)
arraytest2 = arraytest1
arraytest3 = np.copy(arraytest1)
arraytest1[0] = 2
print(arraytest1)
print(arraytest2)
print(arraytest3)

[2 0 0 0 0]
[2 0 0 0 0]
[1 0 0 0 0]
